[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  
  included_files = [
    "node_modules/ffmpeg-static/**/*",
    "node_modules/fluent-ffmpeg/**/*"
  ]
